import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Playfair_Display } from "next/font/google";
import { Climate_Crisis, Bricolage_Grotesque, Manrope } from 'next/font/google';
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  weight: ["600", "700"],
  subsets: ["latin"],
});

const climateCrisis = Climate_Crisis({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-climate',
  display: 'swap',
});

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  variable: '--font-bricolage',
  display: 'swap',
});

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Eventia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider
        appearance={{
          layout: {
            displayLinkExternalId: "none",
            hideExternalLinks: true,
          },
          elements: {
            footerAction: { display: 'none' }
          }
        }}
      >
        <html
      lang="es"
      className={`${climateCrisis.variable} ${bricolage.variable} ${manrope.variable} h-full antialiased`}> 
        <body className="min-h-full flex flex-col">
          {children}</body>
           </html>
    </ClerkProvider > 
  );
}
